- name: Configure Foreman-Katello for Oracle Linux
  hosts: localhost
  gather_facts: false
  vars_files:
    - vars/vault.yml
    - vars/foreman.yml
  tasks:

    - name: Validate Foreman URL is accessible
      uri:
        url: "{{ foreman_server_url }}"
        method: GET
        return_content: false
        validate_certs: "{{ foreman_validate_certs }}"
      register: foreman_url_check
      failed_when:
        - foreman_url_check.status not in [200, 301, 302]
      retries: 3
      delay: 5
      until: foreman_url_check.status in [200, 301, 302]

    - name: Fail if Foreman URL is not accessible
      fail:
        msg: "The Foreman URL {{ foreman_server_url }} is not accessible or invalid."
      when: foreman_url_check.status not in [200, 301, 302]

    - name: Generate GPG key pair in parent directory
      shell: |
        mkdir -p ../gpg_keys
        gpg --batch --homedir ../gpg_keys --generate-key <<EOF
        Key-Type: default
        Subkey-Type: default
        Name-Real: Katello GPG Key
        Expire-Date: 0
        Passphrase: {{ vault_gpg_passphrase }}
        %commit
        EOF
      args:
        creates: ../gpg_keys/pubring.kbx

    - name: Export GPG key to a file
      shell: gpg --homedir ../gpg_keys --armor --export "Katello GPG Key"  --passphrase {{ vault_gpg_passphrase }} > ../gpg_keys/katello-gpg-key.asc
      args:
        creates: ../gpg_keys/katello-gpg-key.asc

    - name: Upload GPG key as Content Credential
      theforeman.foreman.content_credential:
        username: "{{ foreman_username }}"
        password: "{{ vault_foreman_password }}"
        server_url: "{{ foreman_server_url }}"
        validate_certs: "{{ foreman_validate_certs }}"
        name: "Katello GPG Key"
        organization: "{{ organization }}"
        content: "{{ lookup('file', '../gpg_keys/katello-gpg-key.asc') }}"
        content_type: "gpg_key"

    - name: Create Lifecycle Environments
      theforeman.foreman.lifecycle_environment:
        username: "{{ foreman_username }}"
        password: "{{ vault_foreman_password }}"
        server_url: "{{ foreman_server_url }}"
        validate_certs: "{{ foreman_validate_certs }}"
        name: "{{ item.name }}"
        organization: "{{ organization }}"
        prior: "{{ item.prior }}"
      loop: "{{ lifecycle_environments }}"
    
    - name: Create Product for Oracle Linux
      theforeman.foreman.product:
        username: "{{ foreman_username }}"
        password: "{{ vault_foreman_password }}"
        server_url: "{{ foreman_server_url }}"
        validate_certs: "{{ foreman_validate_certs }}"
        name: "{{ product_name }}"
        organization: "{{ organization }}"

    - name: Add Repositories
      theforeman.foreman.repository:
        username: "{{ foreman_username }}"
        password: "{{ vault_foreman_password }}"
        server_url: "{{ foreman_server_url }}"
        validate_certs: "{{ foreman_validate_certs }}"
        name: "{{ item.name }}"
        product: "{{ product_name }}"
        organization: "{{ organization }}"
        url: "{{ item.url }}"
        content_type : "{{ item.content_type }}"
        gpg_key: "Katello GPG Key"
      loop: "{{ repositories }}"

    - name: Synchronize Repositories
      theforeman.foreman.repository_sync:
        username: "{{ foreman_username }}"
        password: "{{ vault_foreman_password }}"
        server_url: "{{ foreman_server_url }}"
        validate_certs: "{{ foreman_validate_certs }}"
        product: "{{ product_name }}"
        organization: "{{ organization }}"
        repository: "{{ item.name }}"
      loop: "{{ repositories }}"

    - name: Create Content Views
      theforeman.foreman.content_view:
        username: "{{ foreman_username }}"
        password: "{{ vault_foreman_password }}"
        server_url: "{{ foreman_server_url }}"
        validate_certs: "{{ foreman_validate_certs }}"
        name: "{{ item.name }}"
        organization: "{{ organization }}"
        repositories: "{{ item.repositories }}"
        state: present
      loop: "{{ content_views }}"

    - name: Publish Content Views
      theforeman.foreman.content_view_version:
        username: "{{ foreman_username }}"
        password: "{{ vault_foreman_password }}"
        server_url: "{{ foreman_server_url }}"
        validate_certs: "{{ foreman_validate_certs }}"
        content_view: "{{ item.name }}"
        organization: "{{ organization }}"
        version: "1.0"
        state: present
      loop: "{{ content_views }}"

    - name: Promote Content Views
      theforeman.foreman.content_view_version:
        username: "{{ foreman_username }}"
        password: "{{ vault_foreman_password }}"
        server_url: "{{ foreman_server_url }}"
        validate_certs: "{{ foreman_validate_certs }}"
        content_view: "{{ item.name }}"
        organization: "{{ organization }}"
        state: present
        lifecycle_environments: "{{ item.promote_to }}"
      loop: "{{ content_views }}"

    - name: Create Activation Keys
      theforeman.foreman.activation_key:
        username: "{{ foreman_username }}"
        password: "{{ vault_foreman_password }}"
        server_url: "{{ foreman_server_url }}"
        validate_certs: "{{ foreman_validate_certs }}"
        name: "{{ item.name }}"
        organization: "{{ organization }}"
        lifecycle_environment: "{{ item.lifecycle_environment }}"
        content_view: "{{ item.content_view }}"
      loop: "{{ activation_keys }}"
