- name: Ensure SELinux is enabled and in enforcing mode
  selinux:
    state: enforcing

- name: Allow HTTPD network connections for Katello
  command: setsebool -P httpd_can_network_connect on

- name: Allow HTTPD to read repository content
  command: setsebool -P httpd_read_user_content on

- name: Add SELinux policy for pulp services
  shell: |
    semanage fcontext -a -t httpd_sys_content_t "/var/lib/pulp(/.*)?"
    restorecon -R /var/lib/pulp
    semanage fcontext -a -t httpd_sys_content_t "/var/www/html/pub(/.*)?"
    restorecon -R /var/www/html/pub
  register: selinux_policy

- name: Ensure SELinux policy is applied
  debug:
    msg: "SELinux configuration complete: {{ selinux_policy }}"
