- name: Check if Katello configuration file exists
  stat:
    path: /etc/foreman-installer/scenarios.d/katello-answers.yaml
  register: katello_file_exists

- name: Check if Katello is installed by looking for initial_admin_password
  command: grep -q 'initial_admin_password:' /etc/foreman-installer/scenarios.d/katello-answers.yaml
  register: initial_admin_password_check
  failed_when: false
  changed_when: false
  when: katello_file_exists.stat.exists

- name: Determine if Katello is installed
  set_fact:
    katello_installed: "{{ initial_admin_password_check.rc == 0 }}"
  when: katello_file_exists.stat.exists

- name: Run Katello installer with customized options
  command:
    cmd: >
      foreman-installer --scenario katello
      --foreman-proxy-puppet false
      --foreman-proxy-tftp false
      --foreman-proxy-dhcp false
      --foreman-proxy-dns false
      --foreman-initial-admin-username admin
      --foreman-initial-admin-password "{{ vault_katello_admin_password }}"
  register: katello_installation
  when: not katello_installed
  ignore_errors: yes

- name: Fail if Katello installation fails
  fail:
    msg: "Katello installation failed. Check logs for details."
  when:
    - not katello_installed
    - katello_installation.rc != 0

- name: Debug admin password
  debug:
    msg: "The Katello admin password is {{ vault_katello_admin_password }}"
