- name: Run Katello installer with customized options
  command:
    cmd: >
      foreman-installer --scenario katello
      --foreman-proxy-puppet false
      --foreman-proxy-tftp false
      --foreman-proxy-dhcp false
      --foreman-proxy-dns false
  register: katello_installation
  ignore_errors: yes


- name: Fail if Katello installation fails
  fail:
    msg: "Katello installation failed. Check logs for details."
  when: katello_installation.rc != 0
