- name: Install system dependencies
  include_tasks: install_dependencies.yml

# - name: Configure SELinux for Katello
#   include_tasks: configure_selinux.yml

- name: Install and configure Katello
  include_tasks: install_katello.yml

# - name: Recreate candlepin KeyStore
#   include_tasks: recreate_candlepin_keystore.yml

# - name: Configure SSL certificates
#   include_tasks: configure_ssl.yml

- name: Sync repositories
  include_tasks: sync_repositories.yml
