- name: Install system dependencies
  include_tasks: install_dependencies.yml

- name: Fix Keyalg issue
  include_tasks: fix_keyalg.yml

- name: Install and configure Katello
  include_tasks: install_katello.yml

- name: Configure firewall
  include_tasks: configure_firewall.yml

# - name: Recreate Candlepin KeyStore
#   include_tasks: recreate_candlepin_keystore.yml

# - name: Configure SSL certificates
#   include_tasks: configure_ssl.yml
