---
# These tasks provide a workaround for a bug in the foreman-installer that causes issues with the keystore
# generation process. For more details, see the discussion here:
# https://community.theforeman.org/t/keytool-error-java-lang-exception-the-keyalg-option-must-be-specified/40247
# This workaround uses an API check to determine if Candlepin is not reachable, and then fixes the keystore.

- name: Check if Candlepin API is reachable
  uri:
    url: https://localhost:23443/candlepin/status
    method: GET
    return_content: yes
    validate_certs: no
  register: candlepin_api_status
  ignore_errors: yes

- name: Debug Candlepin API status
  debug:
    msg: "Candlepin API response: {{ candlepin_api_status.content }}"
  when: candlepin_api_status.status == 200

- name: Check if keystore exists and is empty
  stat:
    path: /etc/candlepin/certs/keystore
  register: keystore_stat
  when: candlepin_api_status.status != 200

- name: Remove empty keystore
  file:
    path: /etc/candlepin/certs/keystore
    state: absent
  when:
    - candlepin_api_status.status != 200
    - keystore_stat.stat.exists
    - keystore_stat.stat.size == 0

- name: Recreate the keystore using OpenSSL
  command: >
    keytool -genkey -storetype pkcs12
    -keystore /etc/candlepin/certs/keystore
    -storepass:file /etc/candlepin/certs/keystore_password-file
    -alias temporary-entry -dname CN=temporary-entry
    -J-Dcom.redhat.fips=false -keyalg RSA
  when: candlepin_api_status.status != 200

- name: Re-run foreman-installer to recreate certificates
  command: >
    sudo foreman-installer --scenario katello --certs-update-all
  when: candlepin_api_status.status != 200
