- name: Create repositories in Katello
  theforeman.foreman.repository:
    username: "{{ foreman_username }}"
    password: "{{ foreman_admin_password }}"
    server_url: "{{ foreman_server_url }}"
    validate_certs: "{{ foreman_validate_certs }}"
    name: "{{ item.name }}"
    product: "{{ product_name }}"
    organization: "{{ organization }}"
    content_type: yum
    url: "{{ item.url }}"
    state: present
  loop: "{{ repositories }}"

- name: Synchronize repositories
  theforeman.foreman.repository_sync:
    username: "{{ foreman_username }}"
    password: "{{ foreman_admin_password }}"
    server_url: "{{ foreman_server_url }}"
    validate_certs: "{{ foreman_validate_certs }}"
    name: "{{ item.name }}"
    product: "{{ product_name }}"
    organization: "{{ organization }}"
  loop: "{{ repositories }}"
