foreman_username: "admin"
foreman_password: "your_password"
foreman_server_url: "https://localhost"
foreman_validate_certs: false
organization: "Default Organization"
product_name: "Default Product"
repositories:
  - name: "CentOS_Base"
    url: "http://mirror.centos.org/centos/7/os/x86_64/"
  - name: "EPEL"
    url: "https://dl.fedoraproject.org/pub/epel/7/x86_64/"
